# Generated by Django 3.2.9 on 2021-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='criado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
