# Generated by Django 3.2.9 on 2021-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_final', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sercico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%d/%m/%Y/')),
                ('criado_por', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
